### ISSUE TITLE
Cannot load such file -- refills/import_generator

### ISSUE THREAD

**Issue by antonioOrtiz** [thoughtbot/refills#55] opened 2014-04-16 00:40 UTC
I am using `bower` to manage my all my libraries and plugins, I believe best practice is to leave all those files `_bower_components` folder for updating and if you're going to port your project. 

Anyway I am wonder if that's my problem. I have a `sass` folder which is linking to the `_bower_components` folder. 

```
@import "../_bower_components/refills/source/stylesheets/all";
```

This is the error I am getting:

```
 Warning: LoadError on line ["1"] of /Users/antonioortiz/Sites/_aortizRefresh_/app/_bower_components/refills/lib/refills.rb: cannot load such file -- refills/import_generator
Run with --trace to see the full backtrace Use --force to continue.
```

Should I just dump the `refills` files in my `sass` folder?

**Comment by teoljungberg** [comment] 2015-01-15 09:47
@antonioOrtiz @woodall @laumontemayor @acoustep @robertjpayne Are you all still experiencing the issues you had? In that case, could you provide me with steps on how to reproduce the issues? The more info I get the easier it would be to solve your issues. Thanks!!

**Comment by teoljungberg** [comment] 2015-01-20 09:16
Closing this for now, I'll gladly re-open the issue again if we can get instructions on how to reproduce the issue. Thanks!

**Comment by timothybuck** [comment] 2015-01-26 07:48
Just hit this issue.  

Steps:
* Using https://github.com/thoughtbot/proteus-middleman
* Added refills to the gem file
```
Timothys-MacBook-Pro-3% more Gemfile
# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source "http://rubygems.org"

gem "middleman"
gem "middleman-livereload"
gem "middleman-deploy"
gem "bourbon"
gem "neat"
gem "refills"

```
* Bundle install
* middleman
```
% middleman
WARN: Unresolved specs during Gem::Specification.reset:
      rack (< 2.0, >= 1.4.5)
      rack-test (~> 0.6.2)
      activesupport (>= 3.1, ~> 4.1.0)
      i18n (>= 0.6.7, ~> 0.6, ~> 0.6.9)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/Users/timothyb/.rvm/gems/ruby-2.1.1/gems/refills-0.0.2/lib/refills/import_generator.rb:1:in `require': cannot load such file -- rails/generators (LoadError)
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/refills-0.0.2/lib/refills/import_generator.rb:1:in `<top (required)>'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/refills-0.0.2/lib/refills.rb:1:in `require'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/refills-0.0.2/lib/refills.rb:1:in `<top (required)>'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `require'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `each'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler/runtime.rb:72:in `block in require'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `each'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler/runtime.rb:61:in `require'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/bundler-1.7.12/lib/bundler.rb:134:in `require'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/middleman-core-3.3.7/lib/middleman-core/load_paths.rb:37:in `setup_load_paths'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/gems/middleman-core-3.3.7/bin/middleman:10:in `<top (required)>'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/bin/middleman:23:in `load'
        from /Users/timothyb/.rvm/gems/ruby-2.1.1/bin/middleman:23:in `<main>'
% 
```
@acoustep's comment seems spot on with what the issue is.

**Comment by teoljungberg** [comment] 2015-01-26 09:41
@timothybuck The gem is packaged to be used with `rails`, which is why you can't load up `middleman`.
Sadly, that leavs middleman out in the cold. 
Support for middleman, and other more minimal frameworks, are not on the roadmap right now. First and foremost we wan to get `1.0.0` out of the door.
As a workaround, copy and paste what you need from http://refills.bourbon.io into the corresponding directory under `source`

I'll reopen the issue as a reminder.

/cc
@antonioOrtiz @woodall @laumontemayor @acoustep @robertjpayne

**Comment by tysongach** [comment] 2017-03-09 00:59
I’m going to re-close. The Refills does not support Middleman for now.

We are working on a re-write for 1.0, but we are not yet sure about delivery/integrations.

**Closed by tysongach** 2017-03-09 00:59 UTC
Labels: new feature
