### ISSUE TITLE
"Nav-link more" items do not appear in chrome 45

### ISSUE THREAD

**Issue by MissionAfrica** [thoughtbot/refills#334] opened 2015-09-11 13:38 UTC
Chrome
![image](https://cloud.githubusercontent.com/assets/9134180/9816064/6c7c7b74-5892-11e5-9852-ce2f94b3ff10.png)

Safari
![image](https://cloud.githubusercontent.com/assets/9134180/9816138/01a2ca46-5893-11e5-8ee2-d6010e9ce569.png)

The "nav-link more" dropdown menu options do not appear on the navigation bar in chrome 45 on OSX.

**Comment by slothbear** [comment] 2015-09-11 21:48
I'm seeing the same thing. I can usually get the `More` menu to return by:

1. Make the window smaller until the mobile `MENU` appears.
1. Open the mobile `MENU`.
1. Hover over the `More` menu to display the submenu.
1. Make the window wider to display the full navigation bar.
1. The `More` menu is back!

**Comment by slothbear** [comment] 2015-09-11 22:43
A somewhat similar issue has been reported in Wordpress Admin. I tried the workaround there (disable slimming paint) and saw no change in our `More` menu.

https://code.google.com/p/chromium/issues/detail?id=509179

**Comment by slothbear** [comment] 2015-09-11 23:20
I've also reproduced the problem in Chrome `Version 47.0.2507.0 canary (64-bit)`. I don't know if it helps or not, but I have another issue in the same menu. Well, an alternate menu in the same location. If the user is signed in, I display the `.nav-link.more` menu (currently invisible, the main issue here).

If no user is signed in, I display a plain `.nav-link` including a [Font Awesome](https://fortawesome.github.io/Font-Awesome/) icon. Since Chrome 45, the icon is missing when the page is loaded, but the *Sign in* link is there. I can get the icon to reappear using the same mobile `MENU` procedure mentioned above.
 
    %li.nav-link
      = icon('facebook-square', '', class: "fa-2x icon-facebook")
      = link_to "Sign in", "/auth/facebook"

Safari:
![image](https://cloud.githubusercontent.com/assets/13285/9828343/df1c6730-58b9-11e5-815c-55acb020b62e.png)

Chrome 45, 47:
![image](https://cloud.githubusercontent.com/assets/13285/9828355/fa3ac516-58b9-11e5-8929-1f57f2983acb.png)

**Comment by rafriki** [comment] 2015-09-15 16:08
@slothbear Will you open a PR for that?

**Comment by slothbear** [comment] 2015-09-15 17:08
The menu and icon function, but the mobile `MENU` has a problem since removing `preserve-3d`. You can see the page contents behind the menu, instead of the menu being opaque. That attribute appears to be doing more than `stop webkit flicker`. I don't like my own workaround much. I wish I could find something in Chrome to point to; perhaps they could fix it.

**Comment by MissionAfrica** [comment] 2015-09-16 07:30
Looking through other issues, #333 suggests adding position:relative to ul.navigation-menu, which works for me. Haven't given it significant testing though.

**Comment by Magnus-G** [comment] 2015-09-18 12:28
@MissionAfrica have you checked to see what happens on an iPhone with that solution? I think maybe the menu breaks there.

**Comment by Magnus-G** [comment] 2015-09-18 12:47
@MissionAfrica I have now merged the solution suggested by @slothbear. To me it looks like the menu works in Chrome, Safari and Firefox and iOS now. Please let me know if it doesn't! 
Closing this for now.

**Closed by Magnus-G** 2015-09-18 12:47 UTC
