### ISSUE TITLE
Accordion Tabs

### ISSUE THREAD

**Issue by shakna-israel** [thoughtbot/refills#210] opened 2015-01-16 02:43 UTC
For some reason, the tabs refill isn't working for me.

I have bourbon and neat installed, and the refill "Centered Navigation" works fine.

You can see what I'm running at http://104.131.8.131 at the moment.

No idea what is going on.

I'm using jQuery 1.11.2.

My SASS import looks like:

@import "bourbon/bourbon";
@import "neat/neat";
@import "refills";
@import "tabs";
@import "screen";

**Comment by Magnus-G** [comment] 2015-01-16 09:55
@shakna-israel seems like the styles of the accordion/tabs aren't present. Try putting them directly in the Sass import file and see if that works before creating a partial for it. If that works, then create the partial and call if in your Sass import. Make sure to use the JS code too since that pattern needs it!

Also, why are you doing a `@import "refills";`? What is in that file? I would recommend putting each component/pattern in a separate file so you can easily reach them and tweak them!

**Comment by Magnus-G** [comment] 2015-01-20 15:15
Closing this. Please re-open if the issue is still around.

**Closed by Magnus-G** 2015-01-20 15:15 UTC

**Comment by shakna-israel** [comment] 2015-01-20 22:47
My bad.

Turns out I was rendering the SASS to the wrong location.
